/**
 * NewContractTypeform — 5-step contract builder wizard
 * Step 1: Party A (Client)
 * Step 2: Party B (Contractor)
 * Step 3: Contract Type & Modules
 * Step 4: Module Questions
 * Step 5: Preview + Chatbot + Sign
 */
import { useState, useCallback } from "react";
import { useLocation } from "wouter";
import { motion, AnimatePresence, useReducedMotion } from "framer-motion";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  ArrowRight,
  ArrowLeft,
  MessageCircle,
  Save,
  Send,
  CheckCircle2,
  Loader2,
  FileText,
  Users,
  Layers,
  HelpCircle,
  Eye,
} from "lucide-react";

import { PartySearch, type PartyData } from "@/components/contract-builder/PartySearch";
import { ModuleSelector } from "@/components/contract-builder/ModuleSelector";
import { ModuleQuestions, type VariableDef } from "@/components/contract-builder/ModuleQuestions";
import { ContractChatbot } from "@/components/contract-builder/ContractChatbot";

// ─── Types ───────────────────────────────────────────────────────────────────

type Category = "freelance" | "home_improvement" | "event_services" | "trade_services" | "other";

const CATEGORIES: { value: Category; label: string; desc: string }[] = [
  { value: "freelance", label: "Freelance / Consulting", desc: "Digital services, design, development, consulting" },
  { value: "home_improvement", label: "Home Improvement", desc: "Construction, renovation, trade works" },
  { value: "event_services", label: "Event Services", desc: "Photography, catering, entertainment, venues" },
  { value: "trade_services", label: "Trade Services", desc: "Electrical, plumbing, heating, specialist trades" },
  { value: "other", label: "Other Services", desc: "General service agreements" },
];

const STEPS = [
  { label: "Client", icon: Users },
  { label: "Contractor", icon: Users },
  { label: "Modules", icon: Layers },
  { label: "Questions", icon: HelpCircle },
  { label: "Preview", icon: Eye },
];

// ─── Slide animation ──────────────────────────────────────────────────────────

const variants = {
  enter: (dir: number) => ({ x: dir > 0 ? 40 : -40, opacity: 0 }),
  center: { x: 0, opacity: 1 },
  exit: (dir: number) => ({ x: dir < 0 ? 40 : -40, opacity: 0 }),
};

const transition = { duration: 0.45, ease: [0.32, 0.72, 0, 1] as const };

// ─── Helpers ──────────────────────────────────────────────────────────────────

function emptyParty(type: "client" | "contractor"): PartyData {
  return { name: "", type: type === "client" ? "client" : "contractor", saveAsProfile: false };
}

function buildPreviewMarkdown(
  partyA: PartyData,
  partyB: PartyData,
  templateName: string,
  selectedClauses: Record<string, string>,
  variables: Record<string, string>
): string {
  const date = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  const clauseList = Object.values(selectedClauses)
    .filter(Boolean)
    .map((id) => `- ${id}`)
    .join("\n");
  const varList = Object.entries(variables)
    .filter(([, v]) => v)
    .map(([k, v]) => `- **${k.replace(/_/g, " ")}**: ${v}`)
    .join("\n");

  return `# SERVICE AGREEMENT

*Dated: ${date}*

---

## Parties

**Client:** ${partyA.name || "[CLIENT NAME]"}
${partyA.companyNumber ? `Company Number: ${partyA.companyNumber}  ` : ""}
${partyA.address ? `Address: ${partyA.address}  ` : ""}
${partyA.email ? `Email: ${partyA.email}` : ""}

**Service Provider:** ${partyB.name || "[PROVIDER NAME]"}
${partyB.companyNumber ? `Company Number: ${partyB.companyNumber}  ` : ""}
${partyB.address ? `Address: ${partyB.address}  ` : ""}
${partyB.email ? `Email: ${partyB.email}` : ""}

---

## Agreement Type

${templateName}

---

## Selected Modules

${clauseList || "Standard clauses apply."}

---

## Contract Details

${varList || "Details to be completed."}

---

## Standard Terms

1. **Payment**: Milestone-based payments held in escrow via AllSquared platform.
2. **Dispute Resolution**: AllSquared AI-assisted mediation, then formal mediation, then courts of England and Wales.
3. **Governing Law**: England and Wales.
4. **Confidentiality**: Both parties agree to maintain confidentiality of proprietary information.
5. **Termination**: 14 days written notice by either party. Outstanding work invoiced on termination.

---

*This is a draft contract generated by AllSquared. Review before signing. Seek independent legal advice for complex matters.*
`;
}

// ─── Main Component ───────────────────────────────────────────────────────────

export default function NewContractTypeform() {
  const [, navigate] = useLocation();
  const reduceMotion = useReducedMotion();
  const [step, setStep] = useState(0);
  const [dir, setDir] = useState(1);
  const [chatOpen, setChatOpen] = useState(false);

  // Party data
  const [partyA, setPartyA] = useState<PartyData>(emptyParty("client"));
  const [partyB, setPartyB] = useState<PartyData>(emptyParty("contractor"));

  // Template/modules
  const [category, setCategory] = useState<Category | "">("");
  const [selectedTemplateId, setSelectedTemplateId] = useState<string>("");
  const [selectedClauses, setSelectedClauses] = useState<Record<string, string>>({});

  // Variables
  const [variableValues, setVariableValues] = useState<Record<string, string>>({});

  // Saving state
  const [saving, setSaving] = useState(false);

  // tRPC
  const savedProfiles = trpc.partyProfiles.list.useQuery();
  const createProfile = trpc.partyProfiles.create.useMutation();
  const createContract = trpc.contracts.create.useMutation();
  const sendForSignature = trpc.contracts.sendForSignature.useMutation();

  const templates = trpc.templateBuilder.listLegalTemplates.useQuery(undefined, {
    enabled: step >= 2,
  });

  const filteredTemplates = templates.data?.filter(
    (t) => !category || t.category === category
  ) ?? [];

  const selectedTemplate = templates.data?.find((t) => t.id === selectedTemplateId);

  const previewMarkdown = buildPreviewMarkdown(
    partyA,
    partyB,
    selectedTemplate?.name ?? category ?? "Service Agreement",
    selectedClauses,
    variableValues
  );

  // ── Navigation ──────────────────────────────────────────────────────────────

  const go = useCallback(
    (next: number) => {
      setDir(next > step ? 1 : -1);
      setStep(next);
    },
    [step]
  );

  const [showValidation, setShowValidation] = useState(false);

  const canAdvance = (): boolean => {
    if (step === 0) return !!partyA.name.trim();
    if (step === 1) return !!partyB.name.trim();
    if (step === 2) return !!category;
    if (step === 3) return true; // questions are optional
    return true;
  };

  const validationMessage = (): string | null => {
    if (step === 0 && !partyA.name.trim()) return "Please enter the client's name to continue.";
    if (step === 1 && !partyB.name.trim()) return "Please enter the contractor's name to continue.";
    if (step === 2 && !category) return "Please select a service category.";
    return null;
  };

  // ── Save handlers ────────────────────────────────────────────────────────────

  const saveProfiles = async () => {
    const saves = [];
    if (partyA.saveAsProfile && partyA.name) {
      saves.push(
        createProfile.mutateAsync({
          name: partyA.name,
          companyNumber: partyA.companyNumber,
          address: partyA.address,
          email: partyA.email,
          phone: partyA.phone,
          type: partyA.type,
          companiesHouseData: partyA.companiesHouseData,
        })
      );
    }
    if (partyB.saveAsProfile && partyB.name) {
      saves.push(
        createProfile.mutateAsync({
          name: partyB.name,
          companyNumber: partyB.companyNumber,
          address: partyB.address,
          email: partyB.email,
          phone: partyB.phone,
          type: partyB.type,
          companiesHouseData: partyB.companiesHouseData,
        })
      );
    }
    if (saves.length > 0) await Promise.all(saves);
  };

  const handleSaveDraft = async () => {
    // Pre-flight: at minimum we need both parties named
    if (!partyA?.name || !partyB?.name) {
      const missing = [
        !partyA?.name && "Party A (client) name",
        !partyB?.name && "Party B (provider) name",
      ].filter(Boolean).join(", ");
      toast.error(`Cannot save: ${missing} required.`);
      return;
    }
    setSaving(true);
    try {
      await saveProfiles();
      await createContract.mutateAsync({
        title: `${partyA.name} ↔ ${partyB.name}`,
        category: (category as Category) || "other",
        description: selectedTemplate?.description || "",
        totalAmount: variableValues["total_amount"] || variableValues["totalAmount"] || "0",
        clientId: partyA.name,
        providerId: partyB.name,
        templateId: selectedTemplateId || undefined,
        contractContent: previewMarkdown,
        selectedClauses: JSON.stringify(selectedClauses),
        filledVariables: JSON.stringify(variableValues),
        generatedMarkdown: previewMarkdown,
        status: "draft",
      } as any);
      toast.success("Contract saved as draft");
      navigate("/dashboard/contracts");
    } catch (e: any) {
      toast.error(e.message || "Failed to save contract");
    } finally {
      setSaving(false);
    }
  };

  const handleSendForSignature = async () => {
    // Pre-flight: party names + email + contract details required
    const missing: string[] = [];
    if (!partyA?.name) missing.push("Party A (client) name");
    if (!partyB?.name) missing.push("Party B (provider) name");
    if (!partyB?.email) missing.push("Party B email");
    if (!variableValues["total_amount"] && !variableValues["totalAmount"]) {
      missing.push("Total contract amount");
    }
    if (missing.length > 0) {
      toast.error(`Cannot send: ${missing.join(", ")} required.`);
      return;
    }

    setSaving(true);
    try {
      await saveProfiles();
      const created = await createContract.mutateAsync({
        title: `${partyA.name} ↔ ${partyB.name}`,
        category: (category as Category) || "other",
        description: selectedTemplate?.description || "",
        totalAmount: variableValues["total_amount"] || variableValues["totalAmount"] || "0",
        clientId: partyA.name,
        providerId: partyB.name,
        templateId: selectedTemplateId || undefined,
        contractContent: previewMarkdown,
        selectedClauses: JSON.stringify(selectedClauses),
        filledVariables: JSON.stringify(variableValues),
        generatedMarkdown: previewMarkdown,
        status: "draft",
      } as any);

      // If we got an id back, immediately call sendForSignature
      const newId = (created as any)?.id || (created as any)?.contractId;
      if (newId && sendForSignature) {
        await sendForSignature.mutateAsync({ id: newId });
        toast.success("Contract sent for signature");
      } else {
        toast.success("Contract saved as draft — open it to send for signature");
      }
      navigate("/dashboard/contracts");
    } catch (e: any) {
      toast.error(e.message || "Failed to send contract for signature");
    } finally {
      setSaving(false);
    }
  };

  // ── Render steps ─────────────────────────────────────────────────────────────

  const profiles = savedProfiles.data ?? [];

  const renderStep = () => {
    switch (step) {
      case 0:
        return (
          <StepShell title="Who is the Client?" subtitle="The party commissioning the work">
            <PartySearch
              label="Client"
              role="client"
              value={partyA}
              onChange={setPartyA}
              savedProfiles={profiles}
            />
          </StepShell>
        );

      case 1:
        return (
          <StepShell title="Who is the Contractor?" subtitle="The party delivering the work">
            <PartySearch
              label="Contractor"
              role="contractor"
              value={partyB}
              onChange={setPartyB}
              savedProfiles={profiles}
            />
          </StepShell>
        );

      case 2:
        return (
          <StepShell title="Contract Type & Modules" subtitle="Choose what applies to this agreement">
            <div className="space-y-5">
              {/* Category selector */}
              <div>
                <label className="text-sm font-medium mb-1.5 block">Service Category</label>
                <Select value={category} onValueChange={(v) => { setCategory(v as Category); setSelectedTemplateId(""); }}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select a category..." />
                  </SelectTrigger>
                  <SelectContent>
                    {CATEGORIES.map((c) => (
                      <SelectItem key={c.value} value={c.value}>
                        <div>
                          <div className="font-medium">{c.label}</div>
                          <div className="text-xs text-muted-foreground">{c.desc}</div>
                        </div>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Template picker */}
              {category && (
                <div>
                  <label className="text-sm font-medium mb-1.5 block">Template (optional)</label>
                  {templates.isLoading ? (
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                      <Loader2 className="w-3.5 h-3.5 animate-spin" /> Loading templates...
                    </div>
                  ) : filteredTemplates.length === 0 ? (
                    <p className="text-sm text-muted-foreground">No templates for this category — standard clauses will apply.</p>
                  ) : (
                    <div className="grid gap-2">
                      {filteredTemplates.map((t) => (
                        <Card
                          key={t.id}
                          className={`cursor-pointer transition-all border ${
                            selectedTemplateId === t.id
                              ? "border-emerald-300 bg-emerald-50/60"
                              : "border-border hover:border-emerald-100"
                          }`}
                          onClick={() => {
                            setSelectedTemplateId(t.id === selectedTemplateId ? "" : t.id);
                            setSelectedClauses({});
                          }}
                        >
                          <CardContent className="flex items-center justify-between p-3">
                            <div>
                              <div className="font-medium text-sm">{t.name}</div>
                              {t.description && (
                                <div className="text-xs text-muted-foreground mt-0.5">{t.description}</div>
                              )}
                            </div>
                            {selectedTemplateId === t.id && (
                              <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                            )}
                          </CardContent>
                        </Card>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {/* Clause bank */}
              {selectedTemplate && (
                <div>
                  <label className="text-sm font-medium mb-2 block">Optional Clauses</label>
                  <ModuleSelector
                    clauseBanks={selectedTemplate.clauseBanks ?? {}}
                    selectedClauses={selectedClauses}
                    onChange={setSelectedClauses}
                  />
                </div>
              )}
            </div>
          </StepShell>
        );

      case 3:
        return (
          <StepShell
            title="Contract Details"
            subtitle="Fill in the specifics for this agreement"
          >
            <ModuleQuestions
              variables={(selectedTemplate?.variables ?? []) as VariableDef[]}
              values={variableValues}
              onChange={setVariableValues}
            />
          </StepShell>
        );

      case 4:
        return (
          <StepShell title="Review & Sign" subtitle="Review your contract and send for signature">
            <div className="space-y-4">
              {/* Preview */}
              <Card className="border-border">
                <CardHeader className="pb-2 flex flex-row items-center justify-between">
                  <CardTitle className="text-sm font-semibold flex items-center gap-1.5">
                    <FileText className="w-4 h-4 text-emerald-500" />
                    Contract Preview
                  </CardTitle>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => setChatOpen(true)}
                    className="text-emerald-600 hover:bg-emerald-50 h-7 px-2"
                  >
                    <MessageCircle className="w-3.5 h-3.5 mr-1" />
                    Ask AI
                  </Button>
                </CardHeader>
                <CardContent className="p-0">
                  <ScrollArea className="h-[380px] px-4 pb-4">
                    <pre className="text-xs text-foreground whitespace-pre-wrap font-mono leading-relaxed">
                      {previewMarkdown}
                    </pre>
                  </ScrollArea>
                </CardContent>
              </Card>

              {/* Party summary */}
              <div className="grid grid-cols-2 gap-3">
                <Card className="border-emerald-50 bg-emerald-50/40">
                  <CardContent className="p-3">
                    <Badge variant="outline" className="text-[10px] border-emerald-200 text-emerald-700 mb-1.5">Client</Badge>
                    <div className="font-medium text-sm">{partyA.name || "—"}</div>
                    {partyA.email && <div className="text-xs text-muted-foreground mt-0.5">{partyA.email}</div>}
                  </CardContent>
                </Card>
                <Card className="border-navy-100 bg-slate-50/60">
                  <CardContent className="p-3">
                    <Badge variant="outline" className="text-[10px] border-slate-400 text-slate-700 mb-1.5">Contractor</Badge>
                    <div className="font-medium text-sm">{partyB.name || "—"}</div>
                    {partyB.email && <div className="text-xs text-muted-foreground mt-0.5">{partyB.email}</div>}
                  </CardContent>
                </Card>
              </div>

              {/* CTA buttons */}
              <div className="flex gap-3 pt-1">
                <Button
                  variant="outline"
                  className="flex-1 border-emerald-100 text-emerald-700 hover:bg-emerald-50"
                  onClick={handleSaveDraft}
                  disabled={saving}
                >
                  {saving ? <Loader2 className="w-4 h-4 mr-1.5 animate-spin" /> : <Save className="w-4 h-4 mr-1.5" />}
                  Save as Draft
                </Button>
                <Button
                  className="flex-1 bg-emerald-600 hover:bg-emerald-700 text-white"
                  onClick={handleSendForSignature}
                  disabled={saving}
                >
                  {saving ? <Loader2 className="w-4 h-4 mr-1.5 animate-spin" /> : <Send className="w-4 h-4 mr-1.5" />}
                  Send for Signature
                </Button>
              </div>
            </div>
          </StepShell>
        );
    }
  };

  // ── Layout ───────────────────────────────────────────────────────────────────

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-emerald-50/30">
      {/* Header with progress */}
      <div className="sticky top-0 z-20 bg-white/90 backdrop-blur border-b border-border">
        <div className="max-w-2xl mx-auto px-4 py-3">
          <div className="flex items-center justify-between mb-2">
            <span className="text-sm font-semibold text-foreground">New Contract</span>
            <span className="text-xs text-muted-foreground">
              Step {step + 1} of {STEPS.length}
            </span>
          </div>
          <Progress value={((step + 1) / STEPS.length) * 100} className="h-1.5" />

          {/* Step pills */}
          <div className="flex gap-1 mt-2.5">
            {STEPS.map((s, i) => {
              const Icon = s.icon;
              return (
                <div
                  key={i}
                  className={`flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium transition-colors ${
                    i === step
                      ? "bg-emerald-600 text-white"
                      : i < step
                      ? "bg-emerald-50 text-emerald-700"
                      : "bg-muted text-muted-foreground"
                  }`}
                >
                  {i < step ? (
                    <CheckCircle2 className="w-3 h-3" />
                  ) : (
                    <Icon className="w-3 h-3" />
                  )}
                  <span className="hidden sm:inline">{s.label}</span>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Step content */}
      <div className="max-w-2xl mx-auto px-4 py-6">
        <AnimatePresence custom={dir} mode="wait">
          <motion.div
            key={step}
            custom={dir}
            variants={variants}
            initial={reduceMotion ? false : "enter"}
            animate="center"
            exit={reduceMotion ? undefined : "exit"}
            transition={transition}
          >
            {renderStep()}
          </motion.div>
        </AnimatePresence>

        {/* Navigation */}
        <div className="flex justify-between mt-6">
          <Button
            variant="ghost"
            onClick={() => go(step - 1)}
            disabled={step === 0}
            className="gap-1.5"
          >
            <ArrowLeft className="w-4 h-4" />
            Back
          </Button>

          {step < STEPS.length - 1 && (
            <div className="flex flex-col items-end gap-1">
              {showValidation && validationMessage() && (
                <p className="text-sm text-destructive">{validationMessage()}</p>
              )}
              <Button
                onClick={() => {
                  if (!canAdvance()) {
                    setShowValidation(true);
                    return;
                  }
                  setShowValidation(false);
                  go(step + 1);
                }}
                className="bg-emerald-600 hover:bg-emerald-700 text-white gap-1.5"
              >
                Continue
                <ArrowRight className="w-4 h-4" />
              </Button>
            </div>
          )}
        </div>
      </div>

      {/* Chatbot */}
      <ContractChatbot
        contractMarkdown={previewMarkdown}
        open={chatOpen}
        onOpenChange={setChatOpen}
      />

      {/* Floating chat button on preview step */}
      {step === 4 && !chatOpen && (
        <button
          onClick={() => setChatOpen(true)}
          className="fixed bottom-6 right-6 bg-emerald-600 hover:bg-emerald-700 text-white rounded-full shadow-lg w-12 h-12 flex items-center justify-center transition-colors z-30"
        >
          <MessageCircle className="w-5 h-5" />
        </button>
      )}
    </div>
  );
}

// ─── Step shell wrapper ───────────────────────────────────────────────────────

function StepShell({
  title,
  subtitle,
  children,
}: {
  title: string;
  subtitle?: string;
  children: React.ReactNode;
}) {
  return (
    <div>
      <div className="mb-5">
        <h1 className="text-xl font-bold text-foreground">{title}</h1>
        {subtitle && <p className="text-sm text-muted-foreground mt-0.5">{subtitle}</p>}
      </div>
      {children}
    </div>
  );
}
